### ISSUE TITLE
请问如何与后端动态数据结合进行打印呢？

### ISSUE THREAD

**Issue by power322** [xinglie/report-designer#30]
感谢大佬这么棒项目!
   目前发现打印方式只能在打印的页面 复制粘贴模板JSON,然后进行打印，找了下没发现相关说明，想请教下我能不能在我的系统定义一个打印按钮,点击后传入后端的动态数据打开打印界面进行打印呢

**Comment by xinglie** [comment]
可以的，可以在你的系统点击打印，把相应内容的id透传到打印页面，在打印页面根据id把相应的模板数据取出来即可打印。
因为在github上我不能模拟动态接口，所以这一部分在展示的demo上并没有体现。

**Comment by power322** [comment]
😭能否给个示例代码,id具体应该怎么传递

**Comment by xinglie** [comment]
这不就是你们做列表页到详情页的事情么？比如你有一个新闻列表，点其中一条到新闻详情页，那你新闻列表页和详情页该怎么做呢？
