### ISSUE TITLE
单元格不能自动换行

### ISSUE THREAD

**Issue by LC95** [xinglie/report-designer#51]
version 202106220825
单元格绑定了一个长字符串，结果点打印时预览发现不能换行，属性那里也没有自动换行，在保存的stage中发现autoReturn为true。
另外使用数据表格的**头**时，能够自动换行，但绑定内容的宽高并不像单元格一样随着单元格的宽高变化。单元格高度增加/减少了，但绑定内容没有增加/减少。修改单元格的宽高之后还需要再去修改里面绑定内容的宽高。这个是有意为之的吗？

**Comment by xinglie** [comment]
单元格会修正，`数据表格`就是这样设计的，如果需要更灵活的表格，你需要使用`自由表格`
