### ISSUE TITLE
富文本打印样式错误

### ISSUE THREAD

**Issue by JaneYork** [xinglie/report-designer#58]
如图
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/29787967/164971428-2a5371a1-c2e5-449f-9633-121f03916c7f.png">

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/29787967/164971431-fad8ddd2-07cc-4fbd-bce9-e94c9ff8181a.png">

**Comment by xinglie** [comment]
这修改这个问题
