### ISSUE TITLE
浏览器打印标签页不管怎么选择都是a4纸

### ISSUE THREAD

**Issue by fanqieo** [xinglie/report-designer#78]
我想一页打印一个标签
![image](https://github.com/xinglie/report-designer/assets/25625919/8dddf681-ab74-47c5-a469-d8fd6e3e509d)
选择了固定页面，预览都正常
但是到浏览器打印的时候
![image](https://github.com/xinglie/report-designer/assets/25625919/d4dbb41c-d9a2-4e6e-b5b5-68c00ea5a566)
又都打印在一个A4纸上了？但是导出PDF又是正常

**Comment by xinglie** [comment]
无论你是直接使用浏览器打印还是通过浏览器的打印导出成pdf文件，都需要在打印的更多设置里，纸张那里使用与设计器中设置的尺寸。

因为浏览器打印时可自由选择纸张尺寸，默认是A4，这个无法通过程序控制，只能自己手动修改浏览器打印时的尺寸

**Comment by xinglie** [comment]
https://github.com/xinglie/report-designer/issues/34
