### ISSUE TITLE
空白编辑区，加一个表格，点击预览会预览编辑页，提示正在计算分页。线上的链接[xinglie.github.io/report-designer]也会有这个效果。

### ISSUE THREAD

**Issue by I-am-JunDa** [xinglie/report-designer#82]
![d7fc01eac4118773061df94be1ca3aa](https://github.com/xinglie/report-designer/assets/57946269/9580ff47-a678-4dd6-a024-aa2237f363d5)
![6d4b103ed9fd57767e79525f1ef2b0f](https://github.com/xinglie/report-designer/assets/57946269/66372324-7766-4ae8-9682-35c8831d42c7)

**Comment by xinglie** [comment]
新版本已修正
